# Generated by Django 5.0.3 on 2024-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_profile_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reputation",
            field=models.IntegerField(default=0),
        ),
    ]
