# Generated by Django 5.0.3 on 2024-05-07 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_profile_login_count_loginsession"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginsession",
            name="login_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 5, 7, 11, 1, 39, 517441, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="loginsession",
            name="logout_at",
            field=models.DateTimeField(null=True),
        ),
    ]
