# Generated by Django 5.0.3 on 2024-05-07 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_loginsession_login_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginsession",
            name="login_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
