# Generated by Django 5.0.3 on 2024-05-07 11:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_loginsession_length"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loginsession",
            name="length",
        ),
    ]
