# Generated by Django 5.0.3 on 2024-03-23 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0002_dictentry_definition"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="dictentry",
            name="definition",
        ),
        migrations.AddField(
            model_name="dictentry",
            name="attributes",
            field=models.ManyToManyField(
                blank=True, related_name="entry", to="dictionary.attribute"
            ),
        ),
        migrations.CreateModel(
            name="Classification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "unique_together": {("code", "name")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="cls",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.classification",
            ),
        ),
        migrations.CreateModel(
            name="Etymology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "unique_together": {("code", "name")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="ety",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.etymology",
            ),
        ),
        migrations.CreateModel(
            name="PartsOfSpeech",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "unique_together": {("code", "name")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="pos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.partsofspeech",
            ),
        ),
    ]
