# Generated by Django 5.0.3 on 2024-03-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0003_attribute_remove_dictentry_definition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="etymology",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name="partsofspeech",
            name="code",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
