# Generated by Django 5.0.3 on 2024-03-23 06:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0004_alter_classification_code_alter_etymology_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="classification",
            old_name="name",
            new_name="meaning",
        ),
        migrations.RenameField(
            model_name="etymology",
            old_name="name",
            new_name="meaning",
        ),
        migrations.RenameField(
            model_name="partsofspeech",
            old_name="name",
            new_name="meaning",
        ),
        migrations.AlterUniqueTogether(
            name="classification",
            unique_together={("code", "meaning")},
        ),
        migrations.AlterUniqueTogether(
            name="etymology",
            unique_together={("code", "meaning")},
        ),
        migrations.AlterUniqueTogether(
            name="partsofspeech",
            unique_together={("code", "meaning")},
        ),
    ]
