# Generated by Django 5.0.3 on 2024-03-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0005_rename_name_classification_meaning_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classification",
            name="code",
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name="etymology",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="partsofspeech",
            name="code",
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
