# Generated by Django 5.0.3 on 2024-03-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0006_alter_classification_code_alter_etymology_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="cls",
        ),
        migrations.RemoveField(
            model_name="attribute",
            name="ety",
        ),
        migrations.AddField(
            model_name="attribute",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.classification",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="etymology",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.etymology",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="entries",
                to="dictionary.partsofspeech",
            ),
        ),
    ]
