# Generated by Django 5.0.3 on 2024-03-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0007_remove_attribute_cls_remove_attribute_ety_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictentry",
            name="word",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
