# Generated by Django 5.0.3 on 2024-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0008_alter_dictentry_word"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="opposite",
            field=models.ManyToManyField(
                null=True, related_name="opposite", to="dictionary.dictentry"
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="similar",
            field=models.ManyToManyField(
                null=True, related_name="similar", to="dictionary.dictentry"
            ),
        ),
    ]
