# Generated by Django 5.0.3 on 2024-04-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0010_alter_attribute_opposite_alter_attribute_similar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictentry",
            name="word",
            field=models.CharField(max_length=100),
        ),
    ]
