# Generated by Django 5.0.3 on 2024-04-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0011_alter_dictentry_word"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictentry",
            name="word",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
