# Generated by Django 5.0.3 on 2024-04-16 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0012_alter_dictentry_word"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="etymology",
        ),
        migrations.AddField(
            model_name="attribute",
            name="origin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.etymology",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="phonetic",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="attribute",
            name="source",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attribute",
            name="classification",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.classification",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="pos",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.partsofspeech",
            ),
        ),
    ]
