# Generated by Django 5.0.3 on 2024-04-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0013_remove_attribute_etymology_attribute_origin_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="phonetic",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="source",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
