# Generated by Django 5.0.3 on 2024-04-20 03:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0014_alter_attribute_phonetic_alter_attribute_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attribute",
            name="phonetic",
        ),
    ]
