# Generated by Django 5.0.3 on 2024-04-20 03:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0015_remove_attribute_phonetic"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Etymology",
            new_name="Origin",
        ),
    ]
