# Generated by Django 5.0.3 on 2024-04-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0016_rename_etymology_origin"),
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictentry",
            name="lang",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dict_entries",
                to="translations.language",
            ),
        ),
    ]
