# Generated by Django 5.0.3 on 2024-04-20 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0021_remove_dictentry_lang"),
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictentry",
            name="lang",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dict_entries",
                to="translations.language",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.classification",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="opposite",
            field=models.ManyToManyField(
                blank=True, related_name="opposite", to="dictionary.dictentry"
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.origin",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attributes",
                to="dictionary.partsofspeech",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="similar",
            field=models.ManyToManyField(
                blank=True, related_name="similar", to="dictionary.dictentry"
            ),
        ),
    ]
