# Generated by Django 5.0.3 on 2024-04-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0022_dictentry_lang_alter_attribute_classification_and_more"),
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictentry",
            name="lang",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dict_entries",
                to="translations.language",
            ),
            preserve_default=False,
        ),
    ]
