# Generated by Django 5.0.3 on 2024-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0023_alter_dictentry_lang"),
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dictentry",
            name="word",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="dictentry",
            unique_together={("word", "lang")},
        ),
    ]
