# Generated by Django 5.0.3 on 2024-04-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0024_alter_dictentry_word_alter_dictentry_unique_together"),
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribute",
            name="example",
            field=models.ManyToManyField(
                blank=True, related_name="example_of", to="translations.entry"
            ),
        ),
    ]
