# Generated by Django 5.0.3 on 2024-04-21 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0025_attribute_example"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attribute",
            old_name="example",
            new_name="examples",
        ),
    ]
