# Generated by Django 5.0.3 on 2024-05-05 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0026_rename_example_attribute_examples"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="dictionary.classification",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="dictionary.origin",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="pos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attributes",
                to="dictionary.partsofspeech",
            ),
        ),
    ]
