# Generated by Django 5.0.3 on 2024-05-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0030_attribute_source"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="origin",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="origin",
            name="code",
            field=models.CharField(max_length=3, null=True, unique=True),
        ),
    ]
