# Generated by Django 5.0.3 on 2024-05-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dictionary", "0031_alter_origin_unique_together_alter_origin_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="dictentry",
            name="last_selected",
            field=models.DateField(blank=True, null=True),
        ),
    ]
