# Generated by Django 5.0.3 on 2024-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0032_dictentry_last_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='origin',
            name='code',
            field=models.CharField(max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='partsofspeech',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
