# Generated by Django 5.0.3 on 2024-03-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0002_language_textentry_delete_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_lang",
                    models.ManyToManyField(
                        related_name="translation_requests", to="translations.textentry"
                    ),
                ),
                (
                    "target_lang",
                    models.ManyToManyField(
                        related_name="translation_responses",
                        to="translations.textentry",
                    ),
                ),
            ],
        ),
    ]
