# Generated by Django 5.0.3 on 2024-03-17 12:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0003_translationentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TranslationEntry",
        ),
    ]
