# Generated by Django 5.0.3 on 2024-03-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0004_delete_translationentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="translations.textentry",
                    ),
                ),
            ],
        ),
    ]
