# Generated by Django 5.0.3 on 2024-03-17 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0005_translationentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="translationentry",
            name="target",
            field=models.ManyToManyField(
                blank=True, related_name="responses", to="translations.textentry"
            ),
        ),
    ]
