# Generated by Django 5.0.3 on 2024-03-17 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0006_translationentry_target"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="textentry",
            unique_together={("content", "lang")},
        ),
    ]
