# Generated by Django 5.0.3 on 2024-03-17 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0007_alter_textentry_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="code",
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="translationentry",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="translations.textentry",
                unique=True,
            ),
        ),
    ]
