# Generated by Django 5.0.3 on 2024-03-17 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0008_alter_language_code_alter_language_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translationentry",
            name="source",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="translations.textentry",
            ),
        ),
    ]
