# Generated by Django 5.0.3 on 2024-03-18 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0014_remove_response_from_request_request_responses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="request",
            name="responses",
        ),
        migrations.AddField(
            model_name="response",
            name="from_request",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="translations.request",
            ),
            preserve_default=False,
        ),
    ]
