# Generated by Django 5.0.3 on 2024-03-18 13:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0015_remove_request_responses_response_from_request"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Request",
            new_name="Text",
        ),
        migrations.RenameModel(
            old_name="Response",
            new_name="Translation",
        ),
        migrations.RenameField(
            model_name="translation",
            old_name="from_request",
            new_name="from_text",
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("content", "lang", "from_text")},
        ),
    ]
