# Generated by Django 5.0.3 on 2024-03-18 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "translations",
            "0016_rename_request_text_rename_response_translation_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="lang",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to="translations.language",
            ),
        ),
        migrations.AlterField(
            model_name="translation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="translations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="texts",
                        to="translations.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="texts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("content", "lang")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="translation",
            name="entry",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="translations.entry",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("content", "lang", "entry")},
        ),
        migrations.RemoveField(
            model_name="translation",
            name="from_text",
        ),
        migrations.DeleteModel(
            name="Text",
        ),
    ]
