# Generated by Django 5.0.3 on 2024-03-25 01:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0019_entry_created_at_translation_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="bookmark",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarks", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
