# Generated by Django 5.0.3 on 2024-03-25 02:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0020_entry_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entry",
            old_name="bookmark",
            new_name="bookmarks",
        ),
    ]
