# Generated by Django 5.0.3 on 2024-03-28 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0022_vote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="translation",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
