# Generated by Django 5.0.3 on 2024-04-15 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0023_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entry",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="translation",
            name="content",
            field=models.TextField(),
        ),
    ]
