# Generated by Django 5.0.3 on 2024-04-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0024_alter_entry_content_alter_translation_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="vote_count",
            field=models.IntegerField(default=0),
        ),
    ]
