# Generated by Django 5.0.3 on 2024-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0025_translation_vote_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="correctness",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entry",
            name="mistake_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="entry",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
