# Generated by Django 5.0.3 on 2024-05-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translations", "0026_entry_correctness_entry_mistake_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="translation",
            name="correctness",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="translation",
            name="mistake_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="translation",
            name="word_count",
            field=models.IntegerField(default=0),
        ),
    ]
