# Generated by Django 5.0.3 on 2024-05-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "translations",
            "0027_translation_correctness_translation_mistake_count_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="translation",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
