# Generated by Django 5.0.3 on 2024-05-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameStats',
        ),
    ]
